function CreateFunctionalPorts(ArchitectureModelName)
    Components(1) = FindComponent(ArchitectureModelName, "Identify Quadcopter Position");
    Components(2) = FindComponent(ArchitectureModelName, "Check Manual Inputs");
    Components(3) = FindComponent(ArchitectureModelName, "Identify Target Position");
    Components(4) = FindComponent(ArchitectureModelName, "Execute Movement");
    
    
    for component = Components
        addPort(component.Architecture, {'inBus', 'outBus'}, {'in', 'out'});
    end
    
    component = FindComponent(ArchitectureModelName, "Plan Movement");
    
    addPort(component.Architecture, {'TargetPosIn', 'TargetPosOut', ...
                                     'CheckInputsIn', 'CheckInputsOut', ...
                                     'ExecuteIn', 'ExecuteOut', ...
                                     'QuadcopterPosIn', 'QuadcopterPosOut', ...
                                     }, { ...
                                     'in', 'out', ...
                                     'in', 'out', ...
                                     'in', 'out', ...
                                     'in', 'out' ...
                                     });
end